package com.nammaexpo.models.enums;

public enum MessageCode {
    USER_REGISTRATION_SUCCESS,
    CREATE_CONTACT_SUCCESS,
    USER_REGISTRATION_FAILED,
    USER_NOT_FOUND,
    CONTACT_DELETE_SUCCESS,
    CONTACT_REGISTRATION_FAILED,
    UPDATE_CONTACT_SUCCESS,
    UPDATE_CONTACT_FAILED,
    EXHIBITION_CREATED,
    EXHIBITION_UPDATED,
    PAGE_CREATED,
    PAGE_UPDATED,
    PROFILE_UPDATED,
    USER_HISTORY_LOGGED
}
