package com.nammaexpo.models.enums;

public enum MessageCode {
  USER_REGISTRATION_SUCCESS,
  CREATE_CONTACT_SUCCESS,
  USER_REGISTRATION_FAILED,
  USER_NOT_FOUND,
  CONTACT_DELETE_SUCCESS,
  CONTACT_REGISTRATION_FAILED,
  UPDATE_CONTACT_SUCCESS,
  UPDATE_CONTACT_FAILED
}
